
CREATE TABLE CARS
(
  COMPANY_NAME VARCHAR(50) NOT NULL COMMENT '회사 이름',
  CAR_NAME     VARCHAR(50) NOT NULL COMMENT '자동차 이름',
  MODEL_YEAR   INTEGER     NOT NULL COMMENT '자동차 연식',
  UNIQUE_ID    VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '자동차';

CREATE TABLE CARS_OPTIONS
(
  OPTIONS        VARCHAR(50) NOT NULL COMMENT '옵션',
  CARS_OPTION_ID VARCHAR(50) NOT NULL COMMENT '자동차_옵션 ID',
  UNIQUE_ID      VARCHAR(50) NOT NULL COMMENT '유니크 ID'
) COMMENT '자동차_옵션';

ALTER TABLE CARS_OPTIONS
  ADD CONSTRAINT FK_CARS_TO_CARS_OPTIONS
    FOREIGN KEY (UNIQUE_ID)
    REFERENCES CARS (UNIQUE_ID);
