
CREATE TABLE CHART_EXAMINATION_RESULT
(
  EXAMINATION_RESULT VARCHAR(50) NOT NULL COMMENT '검진 결과',
  EXAMINATION_ID     VARCHAR(50) NOT NULL COMMENT '검진 결과 ID',
  PRIMARY KEY (EXAMINATION_ID)
) COMMENT '검진 결과';

CREATE TABLE CHART_GENDER
(
  GENDER    VARCHAR(50) NOT NULL COMMENT '성별',
  GENDER_ID VARCHAR(50) NOT NULL COMMENT '성별 ID',
  PRIMARY KEY (GENDER_ID)
) COMMENT '성별';

CREATE TABLE CHART_RE_EXAM_ITEMS
(
  UNIQUE_ID             VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  RE_EXAM_ITEMS_CODE_ID VARCHAR(50) NOT NULL COMMENT '재검진 항목 CODE ID'
) COMMENT '재검진 항목';

CREATE TABLE CHART_RE_EXAM_ITEMS_CODE_ID
(
  RE_EXAM_ITEMS         VARCHAR(50) NOT NULL COMMENT '재검진 항목',
  RE_EXAM_ITEMS_CODE_ID VARCHAR(50) NOT NULL COMMENT '재검진 항목 CODE ID',
  PRIMARY KEY (RE_EXAM_ITEMS_CODE_ID)
) COMMENT '재검진 항목 코드';

CREATE TABLE MEDICAL_CHART
(
  NAME           VARCHAR(50)  NOT NULL COMMENT '이름',
  AGE            INTEGER      NOT NULL COMMENT '나이',
  HEIGHT         INTEGER      NOT NULL COMMENT '키',
  WEIGHT         INTEGER      NOT NULL COMMENT '체중',
  BP             INTEGER      NOT NULL COMMENT '혈압',
  BS             INTEGER      NOT NULL COMMENT '혈당',
  PLAN           VARCHAR(500) NOT NULL COMMENT '유지 방안',
  MEMBER_ID      VARCHAR(50)  NOT NULL COMMENT '환자 ID',
  GENDER_ID      VARCHAR(50)  NOT NULL COMMENT '성별 ID',
  EXAMINATION_ID VARCHAR(50)  NOT NULL COMMENT '검진 결과 ID',
  PRIMARY KEY (MEMBER_ID)
) COMMENT '병원 차트';

ALTER TABLE MEDICAL_CHART
  ADD CONSTRAINT FK_CHART_GENDER_TO_MEDICAL_CHART
    FOREIGN KEY (GENDER_ID)
    REFERENCES CHART_GENDER (GENDER_ID);

ALTER TABLE MEDICAL_CHART
  ADD CONSTRAINT FK_CHART_EXAMINATION_RESULT_TO_MEDICAL_CHART
    FOREIGN KEY (EXAMINATION_ID)
    REFERENCES CHART_EXAMINATION_RESULT (EXAMINATION_ID);

ALTER TABLE CHART_RE_EXAM_ITEMS
  ADD CONSTRAINT FK_MEDICAL_CHART_TO_CHART_RE_EXAM_ITEMS
    FOREIGN KEY (UNIQUE_ID)
    REFERENCES MEDICAL_CHART (MEMBER_ID);

ALTER TABLE CHART_RE_EXAM_ITEMS
  ADD CONSTRAINT FK_CHART_RE_EXAM_ITEMS_CODE_ID_TO_CHART_RE_EXAM_ITEMS
    FOREIGN KEY (RE_EXAM_ITEMS_CODE_ID)
    REFERENCES CHART_RE_EXAM_ITEMS_CODE_ID (RE_EXAM_ITEMS_CODE_ID);
