SELECT T_MEMS.*, T_MEMS_LOGIN.EMAIL, T_GENDERS.GENDER
FROM (members AS T_MEMS
	INNER JOIN members_login AS T_MEMS_LOGIN
    ON T_MEMS.MEMBERS_ID = T_MEMS_LOGIN.MEMBERS_ID
    and T_MEMS.MEMBERS_ID='M-02'    -- WHERE T_MEMS.MEMBERS_ID='M-02'를 제일 아래에 둘 수도 있지만 속도 차이가 나기 때문에 처음부터 넣어주면 좋다.
	)
	INNER JOIN gender_code AS T_GENDERS
    ON T_MEMS.GENDER_CODE_ID = T_GENDERS.GENDER_CODE_ID
  -- WHERE T_MEMS.MEMBERS_ID='M-02'
;
    
--     (members AS T_MEMS
-- 	INNER JOIN members_login AS T_MEMS_LOGIN
--     ON T_MEMS.MEMBERS_ID = T_MEMS_LOGIN.MEMBERS_ID) T_JOIN_MEMS_LOGIN   -- AS T_JOIN_MEMS_LOGIN 해준 것.